spring:
  security:
    oauth2:
      authorization-server:
        issuer: http://localhost:8080
  datasource:
    url: jdbc:postgresql://localhost:5432/banking
    username: postgres
    password: WxzLvtU7Ah25
    hikari:
      data-source-properties:
        encrypt: false
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc:
          batch_size: 500
        order_inserts: true
        order_updates: true
        jdbc.batch_versioned_data: true
        session_factory:
          batch_fetch_size: 500

logging:
  level:
    root: INFO
    org.springframework.security: INFO
    org.springframework.web: INFO
    org.springframework.security.web.FilterChainProxy: INFO
    org.springframework.security.oauth2: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql: INFO

client:
  client-id: 3f5a21d8-84b1-4e7c-b43e-1b02d9c7ef8a
  client-secret: bP9@cZ!6qL#vF2jD$hXt

