spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/banking
    username: postgres
    password: xUZpxA3714D3
    hikari:
      data-source-properties:
        encrypt: false
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
        jdbc.batch_versioned_data: true
        session_factory:
          batch_fetch_size: 50
